import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./components/nav-bar";
import CartProvider from "./context/cart";
import { Toaster } from "@/components/ui/toaster";
import AuthProvider from "./context/auth";
import AssistanceProvider from "./context/assistance";

// import Inter font from Google Fonts
const inter = Inter({ subsets: ["latin"] });

// metadata for the root layout
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// compoenent responsible for wrapping the application content
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-[#eadaa2]">
      <AuthProvider>
          <AssistanceProvider> 
            <CartProvider>
              <NavBar />
              {children}
            </CartProvider>
            <Toaster />
          </AssistanceProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
